services:
  web:
    type: web
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      JWT_SECRET: ${JWT_SECRET}
      UPLOAD_MAX_FILE_SIZE: ${UPLOAD_MAX_FILE_SIZE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}

  postgres:
    type: postgres
    plan: starter
    envVars:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
